dist: trusty
sudo: false
git:
  depth: 10
language: node_js
node_js: 7
cache: yarn
before_install: npm install -g yarn
script: yarn run site
deploy:
  provider: pages
  local_dir: build/site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
