// TODO
// - document aspect navigation configuration
= MuleSoft Docs Site
// Settings
:toc:
:toc-title: Contents
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:important-caption: :exclamation:
:note-caption: :paperclip:
:warning-caption: :warning:
endif::[]
// URIs
:uri-org: https://github.com/ede65566-docs-migration
:uri-repo: {uri-org}/docs-site
:uri-theme-repo: https://github.com/opendevise/mulesoft-docs-theme-default
:uri-ci: https://travis-ci.org/ede65566-docs-migration/docs-site
:uri-site-root: https://ede65566-docs-migration.github.io/docs-site
:uri-site: {uri-site-root}/mule-runtime/3.8
:uri-git: https://git-scm.com
:uri-git-dl: {uri-git}/downloads
:uri-node: https://nodejs.org
:uri-nodegit: http://www.nodegit.org/
:uri-nodegit-dev: http://www.nodegit.org/guides/install/from-source
:uri-nvm: https://github.com/creationix/nvm
:uri-nvm-install: {uri-nvm}#installation
:uri-site-generator: https://gitlab.com/opendevise-projects/opendevise-site-generator-express
:uri-theme-designer-guide: {uri-theme-repo}/blob/master/README.adoc
:uri-theme-user-guide: https://gitlab.com/opendevise-projects/opendevise-site-generator-express/blob/master/docs/theme-user-guide.adoc
:uri-travis-ci: https://travis-ci.org
:uri-yarn: https://yarnpkg.com

This repository hosts the playbook project for generating the new MuleSoft Documentation site ("`docs site`").
It's strictly a configuration as code repository.
That means it does not contain any software, nor does it contain any content.
Instead, it instructs an automated tool how to fetch the software and content it needs and, subsequntly, how to generate the site files.
The repository also includes CI configuration for running the generator and publishing the output files to a web server.

.Disclaimer
WARNING: At the moment, this repository is intended to be used for testing the new site generator pipeline.
Therefore, the files generated from it should only be published to a testing environment.

This document describes the following:

* [x] What prerequisites are needed to bootstrap the site generator.
* [x] How to configure the site generator using the playbook (i.e., configuration file).
* [x] How to execute the site generator.
* [x] How to preview the generated site locally.
* [x] How the CI server is configured to publish the site files.

.Pertinent locations
* {uri-repo}[Site playbook repository] (docs-site)
* {uri-org}[Content repositories] (ede65566-docs-migration)
* {uri-theme-repo}[Default theme repository]
* {uri-ci}[Travis CI job]
* {uri-site}[Published site]

== Overview

The content repositories, the theme repository, the site generator, and the site playbook project are all discrete units in this system.
The site playbook project--this repository--coordinates the other three to produce the site.

The separation of these units is done to keep the logic and configuration separate from the content.
The content repositories are just content.
They can be enlisted into the site generation as needed (per branch), which allows content branches to be easily reused, replaced, deferred, or archived.
This is a sharp contrast with the previous system, which intermixes all of these concerns, making the site difficult to manage, maintain, and enhance.

As much as possible, the site generator takes on the ancillary work previously handled by the (Gradle) build.
For example, it automatically fetches the content repositories as well as the theme used to make the pages.
This is a good thing.
By handling these tasks, it makes this system more CI-friendly, allowing the CI job to focus on preparing the build environment and publishing the output.

In this guide, you'll learn about how these units get joined together to produce the site.

== Prerequisites

The site generator is built entirely atop {uri-node}[Node.js] (herein Node) (command: `node`). 
Therefore, to generate the site, the only software you need on your machine is Node and any system libraries (such as a C compiler) that Node requires in order to install certain Node-based dependencies.

=== Node 7

You must have Node 7 (7.9.0 or better) installed.
Please choose the latest Node 7 release, if possible.

While you can install Node from the official packages, we strongly recommend using {uri-nvm}[nvm] (Node Version Manager) to install and manage Node.
Follow the {uri-nvm-install}[nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a new terminal and install Node 7 using:

 $ nvm install 7

You can switch to this version of Node at any time using:

 $ nvm use 7

To configure Node 7 as the default for any new terminal, define the default alias as follows:

 $ nvm alias default 7

Always verify the version your using is Node 7 (7.9.0 or better) using:

 $ node --version

NOTE: Many CI environments, such as Travis CI, use nvm to install the version of Node used for the build job.
Therefore, by using nvm, you more closely align your setup with the environment that will be used to generate and publish the site.

Despite that fact that Node is required, you won't use it directly.
Instead, you'll interface with Node using a package manager and script runner built on top of it named Yarn.

=== Yarn

{uri-yarn}[Yarn] (command: `yarn`) is the preferred package manager and script runner for the Node ecosystem.

You'll need to use the `npm` command (part of Node) to install Yarn, though this is the last time you'll use the `npm` command.
You should install Yarn globally (which resolves to a location in your user directory if you're using nvm) using:

 $ npm install -g yarn

Verify Yarn is installed by checking the version:

 $ yarn --version

If you see a version, you are all set.

=== git

You need {uri-git}[git] (command: `git`) to pull down the project and push updates to it.

First, check if you have git installed.

 $ git --version

If not, {uri-git-dl}[download and install] the git package for your system.

==== nodegit

Although the site generator interfaces with git repositories, it does not itself require the git command to be available on your system.
Instead, it interacts with git repositories using {uri-nodegit}[nodegit] (JavaScript bindings for libgit2).
Since nodegit is pulled in as a dependency by Yarn, there's no need to worry about installing it.

However, in order for Yarn to install nodegit, you most likely need to have development tools (i.e., a C compiler) installed on your machine.
Details about how to get these libraries can be found in the *Installing Dependencies* section of the page {uri-nodegit-dev}[Building nodegit from source].
Though, if you've already been using your machine for development, you probably already have these tools installed.

Now that you have Node and Yarn installed, you're ready to clone and initialize the playbook project.

== Setting Up the Project

The next step is to fetch the playbook project and initialize it.

=== Fetch

To start, clone the theme project using git:

[subs=attributes+]
 $ git clone --single-branch {uri-repo} &&
   cd "`basename $_`"

Next, you'll need to initialize the project (using Yarn).

=== Initialize

Initializing the project essentially means downloading and installing the dependencies (i.e., required software) for the project.
That's the job of Yarn.

In your terminal, execute the following command (while inside the project folder):

 $ yarn install

The install command uses dependency information defined in [.path]_package.json_ and [.path]_yarn.lock_ to resolve dependencies, which Yarn then installs inside the project under the [.path]_node_modules_ folder.

The playbook project only has one top-level dependency, which is opendevise-site-generator-express.
This dependency is defined in [.path]_package.json_:

[source,json,subs=attributes+]
----
"dependencies": {
  "opendevise-site-generator-express": "{uri-site-generator}#v1.5.0-beta.4"
},
----

The {uri-site-generator}[opendevise-site-generator-express] dependency supplies the main site generator software.
It's preconfigured to generate a documentation site based on <<The Playbook,the playbook>> defined in this project.
The site generator has it's own transitive dependencies, of course, but those get fetched automatically by Yarn.

Let's look at what information the playbook provides, then move on to how to generate the site.

== The Playbook

The playbook tells the site generator the following:

* [x] Which content repositories and branches to feed into the generator.
* [x] Which theme bundle to use to arrange and style the pages.
* [x] The path to aspect navigation domains (navigation which is not linked to a given component).
* [x] The URL of the published site (used for canonical URLs and URLs in the sitemap).

The playbook is the file _site.yml_ at the root of the project.
It is written in YAML, which is a popular configuration language used for configuring automated tasks.
The site generator automatically detects and uses this file (unless you instruct it to use a different file).

Here's the contents of the playbook:

[source,yaml,subs=attributes+]
----
site:
  url: {uri-site-root}
content:
- repository: https://github.com/ede65566-docs-migration/anypoint-connector-devkit-docs.git
- repository: https://github.com/ede65566-docs-migration/anypoint-platform-docs.git
  branches: master
- repository: https://github.com/ede65566-docs-migration/anypoint-studio-docs.git
- repository: https://github.com/ede65566-docs-migration/apikit-docs.git
- repository: https://github.com/ede65566-docs-migration/mule-management-console-docs.git
- repository: https://github.com/ede65566-docs-migration/mule-runtime-docs.git
  branches:
  - v3.8
  - v3.7
- repository: https://github.com/ede65566-docs-migration/munit-docs.git
- repository: https://github.com/ede65566-docs-migration/release-notes-docs.git
- repository: https://github.com/ede65566-docs-migration/runtime-manager-agent-docs.git
- repository: https://github.com/ede65566-docs-migration/solutions-docs.git
- repository: https://github.com/ede65566-docs-migration/tcat-server-docs.git
theme:
  repository: {uri-theme-repo}
nav:
- nav/tutorials.adoc
----

The content key is likely the one you'll tune most often.
It contains an array of repository specifications.
At a minimum, you can specify the location of a (public) repository using the repository key.
The site generator will then scan and use every branch in that repository that begins with "`v`" or matches "`master`".

If you want to limit the branches that are selected, you can specify an array of branch patterns using the branches key.
Each pattern is either an exact branch name or a shell glob pattern such as as `v3.*`.
If the pattern starts with a `!` character, then it is negated. 
This is how you can deselect branches following the use of a glob.

For example, let's say you want to include all 3.x versions except for 3.2.
You'd use the following branches specification:

[source,yaml]
----
branches:
- v3.*
- !v3.2
----

The name of the branch doesn't actually get used by the site generator once it's fetched.
Inside each branch is a [.path]_component.yml_ file.
That file defines the version of the component (i.e., the documentation version).
Thus, you can have more than one branch that provides the same version of the documentation, which you can then toggle between by configuring the branch filter in the playbook.

The theme is configured by pointing to the repository that hosts the theme.
Details about how the theme is created, bundled, published, and consumed can be found in the {uri-theme-designer-guide}[Theme Designer Guide] and the {uri-theme-user-guide}[Theme User Guide].

== Generating the Site

Now that you've told the generator which content to use and what page theme to apply to that content, it's time to run it.

To run the site, you'll invoke the site generator using yarn:

 $ yarn run generator

When generation is complete, you will see a URL in the console (specific to your machine) that you can use to preview the site locally in a browser.

[.output]
....
yarn run v0.27.5
$ node -r opendevise-site-generator-express -e ''
...
Finished in 0:01:46
Site can be viewed at file:///home/user/projects/docs-site/build/site
Done in 106.89s.
....

What happens in the `\...` is explained in the next section.

== The Generator Pipeline

When the generator runs, it performs the following steps:

. Fetches the content repositories using git (via nodegit).
. Resolves and downloads the theme bundle using the GitHub API.
. Locates and reads all AsciiDoc files.
. Locates and reads all navigation files.
. Converts AsciiDoc files to embeddable HTML.
. Wraps the embeddable HTML in the page template and adds the navigation tree, which is also converted to HTML.
. Reads asset files (images, attachments, and theme resources).
. Writes all site files to [.path]_build/site_.

The following sections describe a few of these steps in more detail.

//Q: Should we add a section dedicated to the vinyl collection?

=== Content Fetching

The first step in the site generator--probably the most important--is the fetching of the content.
This is the step that makes this site generator so versatile.
Here's how it works.

The list of repositories is read from the playbook ([.path]_site.yml_).
The site generator then uses git (via nodegit) to clone these repositories.
The cloned repositories are stored under [.path]_build/sources_ (though this may be changed to [.path]_build/content_ in the future).
Currently, the repositories are cloned bare, which means you won't actually see any files inside these directories aside from the [.path]_.git_ folder.

The generator then iterates over all the branches in these repositories and, using information from the playbook, decides which ones it will use.
It then scans those branches and puts the files into a vinyl collection, which is an in-memory collection of virtual file objects.
It associates each file in a branch with the component name and version defined in the [.path]_component.yml_ at the root of the branch.
As such, the repository name and branch name don't matter once the file is read.

The rest of the pipeline interfaces only with this virtual file collection, not the git repositories, thus abstracting away the details of each file's origin.
However, the virtual files do still retain some metadata about each file provided by the git repository.

=== Theme Loading

As described in the {uri-theme-designer-guide}[Theme Designer Guide], each theme bundle is stored as a zip attached to a release in the GitHub repository that hosts the theme.
The generator resolves the latest release of the theme (or, in the future, the specific version specified in the playbook). 
It then downloads the theme bundle attached to that release.
Next, it extracts this zip file and adds the file contents to the vinyl collection previously described.
From that point forward, the pipeline interfaces only with the theme files in the virtual file collection, thus abstracting away the details of the theme's origin.

The theme provides both the design assets (e.g., CSS, fonts, shared images) as well as the template(s) for the pages.
The site generator reads each AsciiDoc document, collects metadata from the document header, converts the document to embeddable HTML, then passes all the information to the template in the form of a page model.
The template then arranges the information and emits a standalone HTML page.
That page is put back into the virtual file collection in place of the AsciiDoc file, now ready to be written to disk as a page in the site.

//Q: add a section to explain sitemap generation?

== CI Hookup

With the files now sitting in [.path]_build/site_, all that's left is to publish them.
This project contains configuration for a {uri-ci}[Travis CI job] that publishes the files in [.path]_build/site_ to GitHub Pages.
Let's look at how that works.

.Disclaimer
IMPORTANT: It's important to emphasize that the site generator is not coupled to Travis or the Travis CI job described here.
The Travis CI job described here simply demonstrates the intent of what needs to happen.
Any CI tool that can publish the files in [.path]_build/site_ can be used instead.

{uri-travis-ci}[Travis CI] (herein Travis) is a continuous integration and automation server designed to tightly integrate with GitHub repositories.
By default, every branch (including pull request branches) of every GitHub repository automatically has a job in Travis associated with it.
All you have to do is flip a switch to enable this integration.

//TODO screenshot
That switch is controlled on the Travis accounts page.
You sign in to Travis using your GitHub credentials and it syncs the repositories automatically.
You just scroll down to the repository you're interested in and flip the switch.
It's that easy.

With Travis activated, every push to the repository triggers a build.
But how does Travis know what to run?
That's the roll of [.path]_.travis.yml_.

Each branch of the repository you intend to use with Travis should have a [.path]_.travis.yml_ configuration file.
This file tells the Travis job what infrastructure to use and what to build.
The default Travis infrastructure is based on Ubuntu (Trusty).
Layered on top of is dedicated language support that allows you to run your job on a specific version of a language (e.g., Node 7 or Ruby 2.4).

If you look at the [.path]_.travis.yml_ file in this repository, you'll see we're using Node 7 on Ubuntu Trusty.

[source,yaml]
----
dist: trusty
# ...
language: node_js
node_js: 7
cache: yarn
----

You'll also see a few lines deal with packages.
It so happens that the Ubuntu Trusty image needs an additional package (installed using apt-get) in order to use nodegit.
This is described using the following lines of configuration:

[source,yaml]
----
addons:
  apt:
    sources: [ ubuntu-toolchain-r-test ]
    packages: [ libstdc++-4.9-dev ]
----

The environment is all set.
What comes next are instructions for how to initialize and run the site generator.

We don't have to tell Travis which repositroy to clone.
It already knows that.
But we can configure how it clones.
Here, we tell it to only clone at a depth of 10, which speeds up the clone and prevents it from taking unnecessary branches.

[source,yaml]
----
git:
  depth: 10
----

Once the repository is cloned, the CI job has to perform the same steps that were described above to run the generator.
Specifically, it:

. Installs Yarn globally:
+
[source,yaml]
----
before_install: npm install -g yarn
----

. Runs `yarn install` (a step implied by enabling the Yarn cache):
+
[source,yaml]
----
cache: yarn
----
+
Subsequent job runs will be accelerated by the use of the Yarn cache, a built-in feature of Travis.

. Executes the site generator:
+
[source,yaml]
----
script: yarn run generator
----

All that remains now is publishing the files in [.path]_build/site_ to GitHub Pages.
Travis provides native integration with GitHub Pages.
All you have to do is tell Travis to use it.
That's where the deploy section comes in:

[source,yaml]
----
before_deploy: touch build/site/.nojekyll
deploy:
  provider: pages
  local_dir: build/site
  project_name: MuleSoft Docs Site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
----

First, we have to touch the [.path]_.nojekyll_ file so that GitHub Pages doesn't do any sort of extra processing of our files.
Next, we activate the GitHub Pages deployment provider (named "`pages`").
We tell it to:

* only run on the master branch,
* where to find the files to publish ([.path]_build/site_),
* not to cleanup these files before publishing (for obvious reasons), and
* which access token to use to write to the git repository.

The token is passed as an environment variable, which we'll get to next.
The files get written to the gh-pages branch of the GitHub repository on which it is running (although this is configurable).

The GITHUB_TOKEN environment variable is configured on the Travis configuration page for this repository.
It gets stored as a _secure_ variable, which means that it's encrypted and not visible in the build logs.
This environment variable gets passed to all builds in the same repository.
The token represents the credentials for the user who will push the commit to the gh-pages branch.
It is also used by the site generator when resolving the latest theme release.

Once published to GitHub Pages, the site is available at {uri-site}.

== Recap

This repository hosts the playbook project for generating the new docs site.
It only contains configuration.
The rest is fetched automatically.

The site generator requires Node 7 to run.
Yarn is used to download and execute the site generator software.
Node and Yarn are the only software packages required.
All other tasks are handled by the site generator.

The site generator uses information in the playbook (i.e., [.path]_site.yml_) to fetch the content and the theme used to arrange and style those pages.
The site files get written to [.path]_build/site_.
The site can be previewed locally out of this location.
Finally, a Travis CI job is used to publish those files to GitHub Pages, where they become available at {uri-site}.
