site:
  url: https://ede65566-docs-migration.github.io/docs-site
content:
- repository: https://github.com/ede65566-docs-migration/anypoint-connector-devkit-docs.git
- repository: https://github.com/ede65566-docs-migration/anypoint-platform-docs.git
  branches: master
- repository: https://github.com/ede65566-docs-migration/anypoint-studio-docs.git
- repository: https://github.com/ede65566-docs-migration/apikit-docs.git
- repository: https://github.com/ede65566-docs-migration/mule-management-console-docs.git
- repository: https://github.com/ede65566-docs-migration/mule-runtime-docs.git
  branches:
  - v3.8
  - v3.7
- repository: https://github.com/ede65566-docs-migration/munit-docs.git
- repository: https://github.com/ede65566-docs-migration/release-notes-docs.git
- repository: https://github.com/ede65566-docs-migration/runtime-manager-agent-docs.git
- repository: https://github.com/ede65566-docs-migration/solutions-docs.git
- repository: https://github.com/ede65566-docs-migration/tcat-server-docs.git
theme:
  repository: https://github.com/opendevise/mulesoft-docs-theme-default
nav:
- nav/tutorials.adoc
